### PR TITLE
Take PUT verb as request method for pypump

### PR DESCRIPTION
**Pull request by samuel-soubeyran**
fixes xray7224/PyPump#121

### CODE REVIEW

**Comment by moggers87** [comment]
Thanks for the PR, looks good.

Would you mind refactoring that whole if-else tree to be a little less repetitive? Something like:

```
fnc =  # get request.<http method>
request = { <params, headers, etc.> }
response = self._requester(fnc=fnc...)
```

Once that's done, I'll be happy to merge.

**Comment by samuel-soubeyran** [comment]
Ok I tried to do what you asked,
tell me if it suits you

**Comment by moggers87** [comment]
Cool, could you move the `if method == "blah"` stuff to before the for loop? `method` doens't change on retry.

**Comment by samuel-soubeyran** [comment]
You are right. Done !

**Comment by moggers87** [comment]
Alright, thanks!

**Pull request merged**
