### PR TITLE
Implement list methods on ItemList

### LINKED ISSUE #125: Error when indexing an activity from an activity list: 'ItemList' object does not support indexing
Hello,

Following the tutorial, I have met some issues trying out Pypump functionalities. Here is one of them about major activities.
>>>recent_activities = me.inbox.major[:30]
>>>for activity in recent_activities:
...        print(activity) 
<Activity: username@pump.io posted note>
<Activity: username@pump.io posted image>
<Activity: username@pump.io posted image>
>>>activity = recent_activities[0]
This is where I get the following error: TypeError: 'ItemList' object does not support indexing

I am familiar with programming in general but Python is new to me and have not found a way to solve that issue myself yet. So my question is, since I have not found any issue concerning this, should this be working in the latest version of Pypump, and if so, how could I fix this?
I am also having other issues about attributes of various instances, commenting notes/images (not going to list them all here, although I could).

Thanks for your time.

### PR DESCRIPTION
**Pull request by moggers87**
Fixes #125 

TODO:

* Unit tests:
  * [x] Unit tests no longer cast Feed slices to lists
  * [x] Slices of slices have not been tested
  * [x] Slices with negative values
  * [x] Negative indices on unsliced Feed objects
* [x] Document the above - there are some caveats

### CODE REVIEW

**Comment by moggers87** [comment]
oh of course ItemList's cache pops results off :)

**Comment by moggers87** [comment]
Current status: tests no longer cast Feeds slices to a list first. However, more testing is required.

**Comment by moggers87** [comment]
There isn't any real documentation around Feed objects, so that should all be added in a separate ticket IMO. Doc strings have been added/updated.

**Comment by kabniel** [comment]
As i am sitting on high ping mobile internet i notice the requests being made when using `ItemList.__getitem__()`, it would be nice if we could use cached items for that but it's not that important.

I think it's ready to be merged.

**Comment by moggers87** [comment]
Yeah, better use of the cache would certainly be a good thing. Open a separate issue for that?

**Pull request merged**
